a = input('\033[1:34mDigite algo: \033[m')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maisculas? ', a.isupper())
print('Está em minusculas?', a.islower())
print('Está capitalizada?', a.istitle())